### ISSUE TITLE
master / live branch - review

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/org-ids#222]
* If we are staying with live, it should be protected? 
* Do we want to move to master, as we have done elsewhere?
* Can we make sure whatever we do is documented well somewhere?

**Comment by Bjwebb** [comment]
I think ideally we should move to master, but the lack of tests puts me off.

**Comment by odscjames** [comment]
Well, actually the process should be:
* delete master branch
* rename live to master
* change salt scripts to deploy "master"
* make sure master is protected in GitHub
* check & update documentation

Then the lack of tests isn't a blocker to sorting this out because nothing should actually change on the live server (but we should tackle tests elsewhere)

Does that sound good?

**Comment by Bjwebb** [comment]
Happy to see this change, this is very much just the way we used to do things. (From back before protected branches were a thing, so that's why that isn't set up).

The point about tests is more about the manual testing in the current workflow: deploy master to the dev site, manually test the dev site, merge into live, then deploy to live. (Manual testing is important because we don't have much automated tests for this). So long as we're happy with the amount of testing in a new workflow, then its fine.

**Comment by odscjames** [comment]
Ah I see, I was confusing automatic testing with manual testing. I understand your point now. We should be able to set up something with branch deploys like we have for CoVE, for manual on-server testing.

**Comment by ghost** [comment]
Early messages here have been overtaken by events.

Our default branch is now "live".

"master" is gone.

For manual testing - https://github.com/OpenDataServices/opendataservices-deploy/blob/main/salt/org-ids.sls#L145 - it's been possible to install extra branches for years.
