### ISSUE TITLE
Deploy at new domain

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/org-ids#36]
Subject to final confirmation, we will be switching the branding of the project to 'org-id' by the end of this sprint.

I think this will require us to:

* [x] Register the new domain (after agreeing the exact domain name and tld to use)
* [x] Point it to the new site
* [ ] Consolidate explanatory from identify-org.net into the new site
* [ ] Move the identify-org.net blog content to run at blog.NEWDOMAIN (still via Wordpress)

**Comment by robredpath** [comment]
@timgdavies do we have a decision on the domain yet?

**Comment by robredpath** [comment]
org-id.guide has been purchased and is in our Gandi account

**Comment by timgdavies** [comment]
Great. I've noted in a few posts ready for tag that the site will be deployed here, so if that can happen by the end of the week that will be great.

**Comment by Bjwebb** [comment]
@robredpath Should the new site have a 'dev banner'? As http://dev.org.prefix.codes/ does

**Comment by robredpath** [comment]
Can we have a 'we welcome your feedback' banner instead?

**Comment by robredpath** [comment]
A 'this is very new and we're still ironing out the bugs, please let us know how you find it' maybe?

**Comment by Bjwebb** [comment]
http://org-id.guide/ is mostly set up, but the DNS may take a few hours to propogate. I've also set up http://dev.org-id.guide/ to point to the dev instance.

Something's broken with the icinga setup, so that needs fixing. Additionally I've noticed that Piwik https://github.com/OpenDataServices/org-ids/issues/57 and Sentry were never set up for the previous dev site, so we should set those up.
